version: '3.1'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_USER=mark
      - MYSQL_PASSWORD=mark
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - my-datavolume:/var/lib/mysql
      - ./phpmyadminVolume/config.inc.php:/etc/phpmyadmin/config.inc.php

  myadmin:
     image: phpmyadmin/phpmyadmin
     restart: always
     ports:
       - 9090:80
     expose:
       - 9090
     links:
       - mysql:db
volumes:
  my-datavolume:
